name: BB Notify Job
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *' # 8:00 JST


jobs:
  run_bb_job:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: node bb
          env:
            BB_ICS_URL: ${{ secrets.BB_ICS_URL }}