name: BB Notify Job
'on':
  push:
    branches:
      - test-run
  schedule:
    - cron: '0 23 * * *' # 8:00 JST


jobs:
  run_bb_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Tokyo"
      - run: node bb
        env:
          BB_ICS_URL: ${{ secrets.BB_ICS_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          BB_ICON_URL: ${{ secrets.BB_ICON_URL }}
          MENTIONID: ${{ secrets.MENTIONID }}
